[package]
name = "crypto-primes"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
description = "Random prime number generation and primality checking library"
repository = "https://github.com/entropyxyz/crypto-primes"
readme = "README.md"
categories = ["cryptography", "no-std"]

[dependencies]
crypto-bigint = { git = "https://github.com/RustCrypto/crypto-bigint", branch = "master", default-features = false, features = ["rand_core"] }
rand_core = { version = "0.6", default-features = false }
getrandom = { version = "0.2", optional = true, default-features = false, features = ["js"] }
openssl = { version = "0.10", optional = true }
rug = { version = "1.18", default-features = false, features = ["integer"], optional = true }

[dev-dependencies]
rand_chacha = "0.3"
criterion = { version = "0.4", features = ["html_reports"] }
num-modular = { version = "0.5", features = ["num-bigint"] }
num-bigint = "0.4"
proptest = "1"
num-prime = "0.4.3"

[features]
default = ["default-rng"]
default-rng = ["getrandom", "rand_core/getrandom"]
tests-openssl = ["openssl"]
tests-gmp = ["rug"]
tests-exhaustive = []
tests-all = ["tests-openssl", "tests-gmp", "tests-exhaustive"]

[[bench]]
name = "bench"
harness = false
