[package]
name = "crypto-primes"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
description = "Random prime number generation and primality checking library"
repository = "https://github.com/entropyxyz/crypto-primes"
readme = "README.md"
categories = ["cryptography", "no-std"]

[dependencies]
crypto-bigint = { git = "https://github.com/RustCrypto/crypto-bigint", branch = "master", features = ["rand"] }
rand_core = { version = "0.6", features = ["getrandom"] }
lazy_static = "1.4"
openssl = { version = "0.10", optional = true }
rug = { version = "1.18", default-features = false, features = ["integer"], optional = true }

[dev-dependencies]
rand_chacha = "0.3"
criterion = { version = "0.4", features = ["html_reports"] }
rand = "0.8"
num-modular = { version = "0.5", features = ["num-bigint"] }
num-bigint = "0.4"
proptest = "1"
number-theory = "0.0.17"

[features]
tests-openssl = ["openssl"]
tests-gmp = ["rug"]

[[bench]]
name = "bench"
harness = false
